### ISSUE TITLE
Workflow with Abstract Action

### ISSUE THREAD

**Issue by devuri** [devuri/rdx-release-deployer-action#44]
We can simplify the user experience by introducing an **abstracted action** that uses sensible defaults while still allowing customization when necessary. This could significantly reduce the number of required inputs. Here's how we can approach it:

### Key Concepts

1. **Default Values**:
   - Use default values for common configuration settings like ports, paths, or usernames.
   - For example:
     - Default SSH port: `22`
     - Default deployment path: `/var/www`
     - Default Slack notification: Disabled if webhook is not provided.

2. **Domain-Based Configuration**:
   - The user provides only a `domain` (or a minimal set of inputs), and the action derives the rest.
   - For instance:
     - If the domain is `staging.example.com`, map it to predefined staging configurations.
     - If the domain is `production.example.com`, map it to production configurations.

3. **Reusable Action**:
   - Create a higher-level composite action (e.g., `abstract-deployer`) that wraps around the deployment logic, applies defaults, and simplifies inputs.

---

### Example: Simplified Workflow with Abstract Action

```yaml
name: 🚀 Simplified Release & Deployment Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to Target Environment
        uses: devuri/abstract-deployer-action@v1
        with:
          domain: ${{ secrets.DEPLOY_DOMAIN }}   # 🌐 Target environment domain (e.g., staging.example.com)
          github-token: ${{ secrets.GITHUB_TOKEN }}  # 🔑 GitHub token
          tag-name: ${{ steps.release.outputs.tag_name }}  # 🏷️ Release tag name
```

---

### Inside the Abstract Action (`abstract-deployer-action`)

The abstract action (`abstract-deployer-action`) can be a **composite action** with logic to set defaults based on the `domain`. Here's an example:

#### `action.yml`
```yaml
name: Abstract Deployer
description: Simplified deployment action with domain-based defaults.
inputs:
  domain:
    description: Domain of the target environment (e.g., staging.example.com)
    required: true
  github-token:
    description: GitHub token for repository access
    required: true
  tag-name:
    description: Release tag name
    required: false
runs:
  using: "composite"
  steps:
    - name: 🛠️ Set Defaults Based on Domain
      run: |
        if [[ "${{ inputs.domain }}" == "staging.example.com" ]]; then
          echo "deploy_path=/var/www/staging" >> $GITHUB_ENV
          echo "deploy_host=staging-server" >> $GITHUB_ENV
          echo "deploy_user=staging-user" >> $GITHUB_ENV
        elif [[ "${{ inputs.domain }}" == "production.example.com" ]]; then
          echo "deploy_path=/var/www/production" >> $GITHUB_ENV
          echo "deploy_host=production-server" >> $GITHUB_ENV
          echo "deploy_user=prod-user" >> $GITHUB_ENV
        else
          echo "Error: Domain not recognized!" >&2
          exit 1
        fi

    - name: 🚀 Execute Deployment
      uses: devuri/rdx-release-deployer-action@v1
      with:
        site-url: ${{ inputs.domain }}
        github-token: ${{ inputs.github-token }}
        deploy-path: ${{ env.deploy_path }}
        deploy-host: ${{ env.deploy_host }}
        deploy-user: ${{ env.deploy_user }}
        deploy-port: 22  # Default port
        deploy-key: ${{ secrets.DEPLOY_KEY }}
        path: build/trunk/
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
```

---

### Benefits of Abstracted Action

1. **Simplified Workflow**:
   - The user only needs to specify the `domain` and `github-token`.
   - Everything else (paths, hosts, users) is derived based on the domain.

2. **Defaults for Flexibility**:
   - Common defaults like the SSH port or deployment paths reduce the need for redundant input.

3. **Reusability**:
   - The abstract action can be reused across different projects with similar configurations.

4. **Error Handling**:
   - If the `domain` doesn’t match a known environment, the action gracefully exits with an error message.

---

### Extending the Action

If more customization is needed, you can:
- Allow users to override specific defaults (e.g., `deploy-path`).
- Add additional logic to handle more complex scenarios (e.g., multi-region deployments).

This approach not only simplifies the configuration for users but also makes the workflow easier to maintain and extend.

**Comment by devuri** [comment]
<html><head></head><body>
<p>The <strong>Abstract Deployer Action</strong> simplifies the deployment process by using defaults based on the target environment's domain. This action eliminates the need to specify repetitive details like paths, ports, and hosts. Users only need to provide a <code inline="">domain</code> and a <code inline="">github-token</code>.</p>

<h2>📋 How to Use</h2>
<h3>Step 1: Add the Workflow File</h3>
<p>Create a workflow file (e.g., <code inline="">.github/workflows/deploy.yml</code>) with the following content:</p>
<pre><code class="language-yaml">name: 🚀 Simplified Deployment Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to Target Environment
        uses: devuri/abstract-deployer-action@v1
        with:
          domain: ${{ secrets.DEPLOY_DOMAIN }}   # 🌐 Target environment domain (e.g., staging.example.com)
          github-token: ${{ secrets.GITHUB_TOKEN }}  # 🔑 GitHub token
          tag-name: ${{ steps.release.outputs.tag_name }}  # 🏷️ Release tag name (optional)
</code></pre>
<hr>
<h3>Step 2: Configure Repository Secrets</h3>
<p>To use this workflow, configure the following <strong>secrets</strong> in your repository settings:</p>

Secret Name | Description
-- | --
DEPLOY_DOMAIN | Target environment domain (e.g., staging.example.com).
DEPLOY_KEY | SSH key for accessing the target server.
SLACK_WEBHOOK | (Optional) Slack webhook URL for deployment notifications.


<hr>
<h3>Step 3: Trigger the Workflow</h3>
<ol>
<li><strong>Automatically</strong>:
<ul>
<li>Close a pull request to trigger the release and deployment workflow.</li>
</ul>
</li>
<li><strong>Manually</strong>:
<ul>
<li>Go to the <strong>Actions</strong> tab, select the workflow, and click <strong>Run Workflow</strong>.</li>
</ul>
</li>
</ol>
<hr>
<h2>🔧 How It Works</h2>
<ol>
<li>
<p><strong>Domain-Based Defaults</strong>:</p>
<ul>
<li>The action derives deployment settings (e.g., <code inline="">path</code>, <code inline="">host</code>, <code inline="">user</code>) based on the provided domain:
<ul>
<li><code inline="">staging.example.com</code> → Defaults for staging.</li>
<li><code inline="">production.example.com</code> → Defaults for production.</li>
</ul>
</li>
</ul>
</li>
<li>
<p><strong>Deployment Execution</strong>:</p>
<ul>
<li>The action uses <a href="https://github.com/devuri/rdx-release-deployer-action">rdx-release-deployer-action</a> for deployment.</li>
<li>Common defaults (e.g., SSH port <code inline="">22</code>, Slack notifications) are applied automatically.</li>
</ul>
</li>
<li>
<p><strong>Override Defaults</strong>:</p>
<ul>
<li>If required, customize the action to add or override settings by extending the logic in the abstract action.</li>
</ul>
</li>
</ol>
<hr>
<h2>Example Use Cases</h2>
<h3>Deploy to Staging</h3>
<p>Set the domain to <code inline="">staging.example.com</code> in <code inline="">DEPLOY_DOMAIN</code> for staging deployment.</p>
<h3>Deploy to Production</h3>
<p>Set the domain to <code inline="">production.example.com</code> in <code inline="">DEPLOY_DOMAIN</code> for production deployment.</p>
<hr>
<h2>Benefits</h2>
<ul>
<li><strong>Simplified Configuration</strong>: Only the <code inline="">domain</code> is needed to deploy.</li>
<li><strong>Environment-Specific Defaults</strong>: Automatically applies settings based on the target domain.</li>
<li><strong>Reusability</strong>: Works across multiple projects with minimal setup.</li>
<li><strong>Notifications</strong>: Supports optional Slack integration for deployment updates.</li>
</ul>
<hr>
<p>Start deploying with ease! 🚀</p></body></html># 🚀 Abstract Deployer Action

The **Abstract Deployer Action** simplifies the deployment process by using defaults based on the target environment's domain. This action eliminates the need to specify repetitive details like paths, ports, and hosts. Users only need to provide a `domain` and a `github-token`.

---

## 📋 How to Use

### Step 1: Add the Workflow File

Create a workflow file (e.g., `.github/workflows/deploy.yml`) with the following content:

```yaml
name: 🚀 Simplified Deployment Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to Target Environment
        uses: devuri/abstract-deployer-action@v1
        with:
          domain: ${{ secrets.DEPLOY_DOMAIN }}   # 🌐 Target environment domain (e.g., staging.example.com)
          github-token: ${{ secrets.GITHUB_TOKEN }}  # 🔑 GitHub token
          tag-name: ${{ steps.release.outputs.tag_name }}  # 🏷️ Release tag name (optional)
```

---

### Step 2: Configure Repository Secrets

To use this workflow, configure the following **secrets** in your repository settings:

| **Secret Name**        | **Description**                                                |
|------------------------|--------------------------------------------------------------|
| `DEPLOY_DOMAIN`        | Target environment domain (e.g., `staging.example.com`).      |
| `DEPLOY_KEY`           | SSH key for accessing the target server.                      |
| `SLACK_WEBHOOK`        | (Optional) Slack webhook URL for deployment notifications.    |

---

### Step 3: Trigger the Workflow

1. **Automatically**:
   - Close a pull request to trigger the release and deployment workflow.
2. **Manually**:
   - Go to the **Actions** tab, select the workflow, and click **Run Workflow**.

---

## 🔧 How It Works

1. **Domain-Based Defaults**:
   - The action derives deployment settings (e.g., `path`, `host`, `user`) based on the provided domain:
     - `staging.example.com` → Defaults for staging.
     - `production.example.com` → Defaults for production.

2. **Deployment Execution**:
   - The action uses [[rdx-release-deployer-action](https://github.com/devuri/rdx-release-deployer-action)](https://github.com/devuri/rdx-release-deployer-action) for deployment.
   - Common defaults (e.g., SSH port `22`, Slack notifications) are applied automatically.

3. **Override Defaults**:
   - If required, customize the action to add or override settings by extending the logic in the abstract action.

---

## Example Use Cases

### Deploy to Staging
Set the domain to `staging.example.com` in `DEPLOY_DOMAIN` for staging deployment.

### Deploy to Production
Set the domain to `production.example.com` in `DEPLOY_DOMAIN` for production deployment.

---

## Benefits

- **Simplified Configuration**: Only the `domain` is needed to deploy.
- **Environment-Specific Defaults**: Automatically applies settings based on the target domain.
- **Reusability**: Works across multiple projects with minimal setup.
- **Notifications**: Supports optional Slack integration for deployment updates.

---

Start deploying with ease! 🚀
